### ISSUE TITLE
Issues with RaspberryPi OS?

### ISSUE THREAD

**Issue by imacomputa** [adangert/JoustMania#326]
Hi,
I just set this up with a Pi4 and am using these Bluetooth adapters:
https://a.co/d/0c4dUT0j
https://a.co/d/075vnmVO (but an older model, 4.0).

I had an issue with the script to enable AP mode. While running the script it eventually closed and restarted the Pi, but with Wi-Fi still enabled and AP not active upon restart. Not a big deal but I wondered if there have been changes to the OS that may be causing issues.

My bigger issue is that I can't seem to reliably pair more than 5 motion controllers. I was eventually able to get all 8 paired and active last night, but when it was showtime today at the cookout only 5 would connect. 

Any help would be greatly appreciated! It's an awesome project and I was really excited when I stumbled upon it the other day. 

Thanks

**Comment by adangert** [comment]
Hey thanks for reaching out!

I've definitely found that the quality of bluetooth dongles is important for how many controllers you can connect at once, I trust the TRENDnet versions, so I would suspect that the ZEXMTE one you have might only allow for 2-3 connections, which is why you are only able to connect so few. I would recommend getting try different dongles, you can also look in  the `/var/lib/bluetooth` folder to see where controllers are hooked up, and which ones are syncing or not, which should give you some indication if one of the dongles can't support more controllers.

Also what could help is getting small extension cords (2-3 inches) for each of the bluetooth dongles to reduce interference between them.

Hope this helps! for the AP mode, try going the ip address listed after running `ifconfig` in the terminal, in the pi browser to see if that helps! Enjoy the jousting!
