### ISSUE TITLE
PSMove Controllers not pairing

### ISSUE THREAD

**Issue by thexant** [adangert/JoustMania#94]
Title says it all, PSMove controllers not turning white or syncing with the Pi.

Did everything as the setup said to do.

**Comment by adangert** [comment]
Looking into it

**Comment by adangert** [comment]
make sure you are running with the a raspberry pi 3 b, and running the latest raspian stretch image. I just tested it out on a clean install and everything seems to be working. Also some new pairing code was just added, so that may help. If nothing seems to be working you could try running joustmania manually here: https://github.com/adangert/JoustMania/blob/master/DEVELOPMENT_README.md
and see if you are getting any errors.
